"""Smoke-execute every notebook's jupytext .py:percent mirror.

Each notebook is run as a subprocess (clean interpreter per notebook) with
NEUROVLM_SMOKE=1, which caps training loops to one epoch over a couple of
batches (see smoke_bootstrap.py) so real data/model code paths get exercised
in seconds instead of hours. This does not validate numerical quality; it
only proves the notebook's code still runs after refactors.

Separate from the fast deterministic suite: run explicitly with

    pytest tests/notebooks -m notebook_smoke -v

Not part of the default `pytest` collection filter used in CI.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = REPO_ROOT / "docs"
RUNNER = Path(__file__).parent / "run_smoke.py"

DEFAULT_TIMEOUT = 300

# Notebooks with heavier-than-default real work (large model downloads,
# generation, or embedding builds) that legitimately need more wall time even
# at smoke scale (batches are capped, but e.g. loading a full corpus or an LLM
# checkpoint is not).
TIMEOUT_OVERRIDES: dict[str, int] = {
    "01_tutorials/04_generative_brain-to-text.py": 600,
    "03_models/13_qformer_pubmed.py": 900,
    "03_models/14_qformer_anat.py": 900,
    "03_models/11_anatomical_atlases.py": 600,
    "figures/24_brain_to_text_pubmed.py": 900,
    "figures/20_pubmed_cv.py": 900,
    "experimental/evaluation/17_qualatative_generative.py": 900,
    "experimental/evaluation/18_quant_gen_a.py": 900,
    "experimental/evaluation/18_quant_gen_b.py": 900,
    "experimental/data_preparation/extract_neuroscience_terms_from_text.py": 600,
}

# Notebooks that cannot run in this environment/checkout regardless of scale
# (missing source file, external repos/data not vendored here). Keep in sync
# with docs/figures/README.md and docs/experimental/README.md.
KNOWN_UNRUNNABLE: dict[str, str] = {
    "figures/23_versus_others.py": "requires external NiCLIP/NeuroConText baseline installs not vendored in this repo",
    "experimental/evaluation/18_quant_gen_b.py": "documented as requiring an unpublished quantitative-eval baseline; see notebook header",
    "02_data/03_neurovault.py": (
        "reads pre-scraped raw artifacts (neurovault_collections.parquet, "
        "neurovault_images.parquet, neurovault_abstracts.parquet) that are not part of "
        "the fetch_data() release bundle and are not present in this checkout; only "
        "reproducible via the notebook's rescrape=True branch, which hits the live "
        "Neurovault/Crossref APIs and is far outside smoke scope"
    ),
    "02_data/06_n_grams.py": (
        "reads corpus.txt, a manually curated term list produced by a human-in-the-loop "
        "review step (see the commented-out generation cell above the read); not an "
        "artifact this repo can regenerate automatically"
    ),
    "02_data/07_transform_text.py": (
        "loads meta-llama/Meta-Llama-3.1-8B-Instruct (gated, 8B params) to batch-generate "
        "summaries over the full PubMed corpus; impractical to smoke test without a GPU"
    ),
    "03_models/10_n_grams.py": (
        "reads ngram_emb.pt produced by 02_data/06_n_grams.py, which is itself skipped "
        "(requires manually curated corpus.txt)"
    ),
    "03_models/13_qformer_pubmed.py": (
        "reads neuro_summaries.parquet produced by 02_data/07_transform_text.py, which is "
        "itself skipped (requires an 8B-parameter gated LLM)"
    ),
    "03_models/14_qformer_anat.py": (
        "reads text_synth_less.parquet, which has no producer notebook anywhere in this "
        "repo (not generated by 11_anatomical_atlases.py or any other tracked notebook)"
    ),
    "experimental/data_preparation/extract_neuroscience_terms_colab_hf.py": (
        "Colab-only notebook: uses IPython shell magics (!git clone, %cd), mounts Google "
        "Drive, and requires an A100 GPU; not runnable as a plain script by design"
    ),
    "experimental/data_preparation/mesh.py": (
        "reads unified_kg_nodes.parquet from ../../../experiments/data/unified_kg, a path "
        "outside this repo's tracked tree that isn't present in this checkout"
    ),
    "experimental/evaluation/14_llm_concepts.py": (
        "reads concept_clf.pt produced by 03_models/10_n_grams.py (itself skipped) and "
        "networks_arrays.pkl.gz, then loads meta-llama/Meta-Llama-3.1-8B-Instruct; hangs "
        "indefinitely with no output on this machine (observed >2h, no GPU) even before "
        "considering the missing upstream artifact"
    ),
    "experimental/evaluation/17_qualatative_generative.py": (
        "reads neurovault.pt produced by 02_data/03_neurovault.py, which is itself skipped "
        "(requires pre-scraped raw Neurovault artifacts not in this checkout)"
    ),
    "experimental/evaluation/18_quant_gen_a.py": (
        "reads neuro_vault_brain_to_text.csv, which has no producer notebook anywhere in "
        "this repo"
    ),
    "experimental/evaluation/15_qualatative_networks.py": (
        "reads networks_emb.pt, generated only inside 14_llm_concepts.py (itself skipped: "
        "needs concept_clf.pt from the blocked 10_n_grams.py chain plus a gated 8B LLM)"
    ),
    "figures/11_autoencoder.py": (
        "reads neurovault.pt produced by 02_data/03_neurovault.py, which is itself skipped "
        "(requires pre-scraped raw Neurovault artifacts not in this checkout)"
    ),
    "figures/19_ica_networks.py": (
        "reads networks_emb.pt, generated only inside 14_llm_concepts.py (itself skipped: "
        "needs concept_clf.pt from the blocked 10_n_grams.py chain plus a gated 8B LLM)"
    ),
    "figures/16_qualatative_auto.py": (
        "reads network_examples.csv, a hand-curated selection with no producer notebook "
        "anywhere in this repo"
    ),
    "figures/20_pubmed_cv.py": (
        "reads ngram_labels.npy produced by 03_models/10_n_grams.py, which is itself "
        "skipped (requires manually curated corpus.txt upstream)"
    ),
    "figures/24_brain_to_text_pubmed.py": (
        "generates text for the full PubMed test-image corpus via nvlm.generate_text "
        "(no smoke-scale cap in the notebook) then runs bert_score/SentenceTransformer "
        "scoring; observed to still exceed 900s with no output after fixing the "
        "hardcoded-cuda bug, consistent with docs/figures/README.md flagging this class "
        "of notebook as substantially more expensive than artifact-loading notebooks"
    ),
}


def _discover_notebooks() -> list[Path]:
    return sorted(DOCS_ROOT.rglob("*.ipynb"))


def _relative_py(nb_path: Path) -> Path:
    return nb_path.relative_to(DOCS_ROOT).with_suffix(".py")


NOTEBOOKS = _discover_notebooks()


def _marks_for(rel_key: str) -> list:
    marks = [pytest.mark.notebook_smoke, pytest.mark.slow, pytest.mark.network]
    if rel_key in KNOWN_UNRUNNABLE:
        marks.append(pytest.mark.skip(reason=KNOWN_UNRUNNABLE[rel_key]))
    return marks


def _params():
    for nb in NOTEBOOKS:
        rel_key = str(_relative_py(nb))
        yield pytest.param(nb, id=rel_key, marks=_marks_for(rel_key))


@pytest.mark.parametrize("notebook_path", list(_params()))
def test_notebook_smoke(notebook_path: Path):
    py_path = notebook_path.with_suffix(".py")
    assert py_path.is_file(), f"missing jupytext mirror for {notebook_path}; run `jupytext --sync {notebook_path}`"

    rel_key = str(_relative_py(notebook_path))
    timeout = TIMEOUT_OVERRIDES.get(rel_key, DEFAULT_TIMEOUT)

    env = dict(os.environ)
    env["NEUROVLM_SMOKE"] = "1"
    env["MPLBACKEND"] = "Agg"
    env["TOKENIZERS_PARALLELISM"] = "false"
    env["PYTHONPATH"] = str(REPO_ROOT) + os.pathsep + env.get("PYTHONPATH", "")

    result = subprocess.run(
        [sys.executable, str(RUNNER), str(py_path)],
        cwd=py_path.parent,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )

    if result.returncode != 0:
        tail_out = "\n".join(result.stdout.splitlines()[-60:])
        tail_err = "\n".join(result.stderr.splitlines()[-60:])
        pytest.fail(
            f"{rel_key} exited {result.returncode}\n--- stdout (tail) ---\n{tail_out}\n"
            f"--- stderr (tail) ---\n{tail_err}"
        )
